INSERT INTO ACCOUNT (ID, ACCOUNT_NUMBER, BALANCE, OVERDRAFT, PIN) VALUES (1, 123456789, 800, 200, 1234);
INSERT INTO ACCOUNT (ID, ACCOUNT_NUMBER, BALANCE, OVERDRAFT, PIN) VALUES (2, 987654321, 1230, 150, 4321);
INSERT INTO ATM (ID) VALUES (1);
INSERT INTO ATM_DENOMINATION_AMOUNT_MAP (ATM_ID, DENOMINATION_AMOUNT_MAP, DENOMINATION) VALUES (1, 20, 5);
INSERT INTO ATM_DENOMINATION_AMOUNT_MAP (ATM_ID, DENOMINATION_AMOUNT_MAP, DENOMINATION) VALUES (1, 30, 10);
INSERT INTO ATM_DENOMINATION_AMOUNT_MAP (ATM_ID, DENOMINATION_AMOUNT_MAP, DENOMINATION) VALUES (1, 30, 20);
INSERT INTO ATM_DENOMINATION_AMOUNT_MAP (ATM_ID, DENOMINATION_AMOUNT_MAP, DENOMINATION) VALUES (1, 10, 50);